// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thdpqwucjphkxqfqitub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoZHBxd3VjanBoa3hxZnFpdHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTMyNjYsImV4cCI6MjA3NDM4OTI2Nn0.cRxMTdPcZNMszaHpnh-g4IqgLJhezvl3hCMo5Qr9u_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});